mysql:
    host: localhost
    username: root
    password: secret
    database: geoloqi_backup
    encoding: UTF8

geoloqi:
    access_key: 'see README.md for additional info'
    results_count: 1000

map:
    max_accuracy: 50
    big_dot_level: 3000